<?php
/*******************************************************************************
 * Copyright (c) 2017.
 * this file created in printing-office project
 * framework: Yii2
 * license: GPL V3 2017 - 2025
 * Author:amintado@gmail.com
 * Company:shahrmap.ir
 * Official GitHub Page: https://github.com/amintado/printing-office
 * All rights reserved.
 ******************************************************************************/

/**
 * Created by PhpStorm.
 * User: amin__000
 * Date: 9/3/2017
 * Time: 7:34 PM
 */

namespace amintado\inquery\models\behaviors;


use yii\behaviors\AttributeBehavior;
use yii\db\BaseActiveRecord;

class DeletedBehavior extends AttributeBehavior
{
    public $deleted_by=0;

    public function init()
    {
        parent::init();

        if (empty($this->attributes)){
            $this->attributes=
                [
                    BaseActiveRecord::EVENT_BEFORE_INSERT=>[$this->deleted_by]
                ];
        }
    }

    protected function getValue($event)
    {
        if (!empty($this->value)){
            return $this->value;
        }
        return parent::getValue($event); // TODO: Change the autogenerated stub
    }
}