<?php
/*******************************************************************************
 * Copyright (c) 2017.
 * this file created in printing-office project
 * framework: Yii2
 * license: GPL V3 2017 - 2025
 * Author:amintado@gmail.com
 * Company:shahrmap.ir
 * Official GitHub Page: https://github.com/amintado/printing-office
 * All rights reserved.
 ******************************************************************************/

/**
 * Message translations.
 *
 * This file is automatically generated by 'yii message/extract' command.
 * It contains the localizable messages extracted from source code.
 * You may modify this file by translating the extracted messages.
 *
 * Each array element represents the translation (value) of a message (key).
 * If the value is empty, the message is considered as not translated.
 * Messages that no longer need translation will have their translations
 * enclosed between a pair of '@@' marks.
 *
 * Message string can be used with plural forms format. Check i18n section
 * of the guide for details.
 *
 * NOTE: this file must be saved in UTF-8 encoding.
 */
return [
    'Confirmation' => 'تایید',
    'Information' => 'اطلاعات',
    'Ok' => 'تایید',

    'Inqueries' => 'لیست استعلام قیمت',
    'qdate' => 'تاریخ درخواست',
    'Uid' => 'نام کاربری',
    'Category' => 'موضوع استعلام',
    'Taban inquery category' => 'دسته ی موضوعی استعلام',
    'Choose Taban inquery category' => 'موضوع استعلام را انتخاب کنید',
    'No Submitted Data' => 'اطلاعاتی ارسال نشده است',
    'qdescription' => 'متن درخواست',
    'Inquery' => 'استعلام',
    'Inquery in time' => 'نمایش استعلام گرفته شده در تاریخ',
    'request data' => 'اطلاعات درخواست',
    'request text' => 'متن درخواست',
    'qfile' => 'فایل پیوست',
    'category' => 'موضوع استعلام',
    'answer' => 'پاسخ استعلام',
    'adescription' => 'متن پاسخ',
    'Bad Confirm request' => 'متاسفانه این درخواست وجود ندارد',
    'status' => 'وضعیت',
    'status wait' => 'در انتظار',
    'status viewed' => 'در حال بررسی',
    'status answered' => 'پاسخ داده شد',
    'Create Inquery' => 'استعلام جدید',
    'Create' => 'ارسال',
    'Cancel' => 'لغو',
    'user name' => 'نام کاربری',
    'user fullname' => 'نام کاربر',
    'user data' => 'اطلاعات کاربر',
    'confirm status success alert' => 'این درخواست قبلا تایید شده است و قابل بررسی نیست',
    'Inquery Categories' => 'دسته بندی موضوعی استعلام ها',
    'Create Inquery Category' => 'ثبت موضوع جدید',
    'full' => 'کامل',
    'export all data' => 'استخراج همه ی داده ها',
    'Catname' => 'موضوع',
    'Description' => 'توضیحات',
    'Catname placeholder' => 'موضوع خود را درج کنید',
    'Inquery Category' => 'موضوع استعلام',
    'Update'=>'بروزرسانی',
    'Delete'=>'حذف'
];
